"""
Django settings for myresite project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/

Run with DJANGO_SETTINGS_MODULE=myresite.prod_settings
"""

from myresite.common_settings import *
import os
from django.utils.crypto import get_random_string

# SECURITY WARNING: keep the secret key used in production secret!
try:
    from myresite import secret_key
    SECRET_KEY=secret_key.SECRET_KEY
except ImportError:
    chars = 'abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)'
    SECRET_KEY = get_random_string(50, chars)
    with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'secret_key.py'), 'w') as f:
        f.write('SECRET_KEY="{}"\n'.format(SECRET_KEY))
    from myresite import secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

import server_ip
ALLOWED_HOSTS = [
                # '127.0.0.1',
                 server_ip.SERVER_IP,
                 ]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
#MAKE SURE that www-data has execution priviliges on all folders leading to static folder, or 403 will be raised.

from myresite import static_root
STATIC_ROOT = static_root.STATIC_ROOT
print("STATIC_ROOT", STATIC_ROOT)#debug

# SECURITY SETTINGS

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'

# SSL/HTTPS measures
# A tuple representing a HTTP header/value combination that signifies a request is secure.
# A header will be provided by nginx by setting `proxy_set_header X-Forwarded-Proto $scheme;`
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True  # so that requests over HTTP are redirected to HTTPS

# This instructs the browser to only send cookies over HTTPS connections.
# Note that this will mean that sessions will not work over HTTP,
# and the CSRF protection will prevent any POST data being accepted over HTTP
# (which will be fine if you are redirecting all HTTP traffic to HTTPS).
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True

#TODO: test these options, they are said to be unsafe.
# SECURE_HSTS_SECONDS = 3600
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
